### ISSUE TITLE
Feature Request/User Experience Improvement - Fractional rain is a must in an FWI/FBP calculator.

### ISSUE THREAD

**Issue by spydmobile** [Sybrand/Sybrand#1]
Thank you for creating and sharing this tool.

Some constructive criticism. You should not enforce rounding on inputs. For serious use this is a roadblock.
From an operational fire modeller and fire science developers perspective, Fractional rain and windspeed matters. Fractional FWI does not, 
When My rain is 2.5mm I am forced to use FPBgo twice, once for 2mm and once for 3mm to validate the FFMC for 2.5m while this might seem a savings on coding and interface, it is a detriment to the tool and the user experience. its also kind of silly to enforce a brutal rounding to a whole number for values that are fractional in the equations, then to output the FFMC to 14 decimal places.
I think you should implement this improvement and let your inputs have 1 decimal, and if you must, give your FWI one decimal too, but certainly not 14

**Comment by Sybrand** [comment]
@spydmobile thank you for the feedback.

> Disclaimer: I no longer work for the Government of British Columbia, so my response is purely my personal opinion. For official communication please refer: to https://github.com/bcgov/fbp-go , or reach out directly to the BCWS Predictive Services Unit.

I was un-aware that anyone was using the instance hosted on https://sybrand.github.io/ - this was really intended as an easy testing space. The official release is available on the Apple iStore and on the Android Play Store.

If you and others, are actively using https://sybrand.github.io/ then I'd be happy to engage and address the issues you've raised. It may even be possible to push the changes upstream to the official repository. It would also make sense to move the tool to a more permanent URL.

My time is very limited though, so I'd only want to do so if there is serious interest out there in using and growing the tool.

# re. rounding inputs.

FBP Go is intended for field use (think thick, dirty, grubby fingers), as such a decision was made to make the input as simple and basic as possible. Think of it as an alternative to the Red Book for a CL. The idea being, that if someone in the field wants a rough understanding of what the fire might be doing, 0.5mm isn't going to make a big different to their day.

There was a lot of internal discussion around the possibility of an "advanced" screen, but it was decided against assuming that anyone who was doing "serious" modelling, would be using other tools.

I could easily add an "advanced" mode that replaces the sliders with input fields for exact numbers.

# re. decimal places.

100% correct. What you're looking at is an early testing release. I started adding FWI in my last days there. It was my intention to complete FWI, and possible more features before leaving the employment of BC Gov, but I didn't have the time.

What you're seeing there - is me testing to see if the FFMC output is working correctly. If there is any interest in taking this further I'd be happy to talk.

**Comment by spydmobile** [comment]
Hi, I had no idea that this was not the official tool LOL, My own fault for not asking, as I got it (The link) from Neal, and should have simply asked him about it. When he first told us (The national modelling team), about it, I posted the URL in our discord in our list of helpful modelling tools, and since then I use it every day (Please do not feel any obligation because of this - I know what it is like to maintain a GitHub project past its intended purpose and expected prototype lifecycle, as many of the critical tools NWT uses are exactly that, prototypes that worked too well to die, that became mission critical tools.)

I do not want you to feel any extra pressure to work on this project, as a thick & dirty fingers tool, it works perfectly. But.... there are a select few, mostly the WISE & CWFIS teams nerds (my self included) that likely pop the tool open to do quick validations of FWI etc. So it has a few users despite the fact that the codebase has moved on to BC Apps on mobile.

Lastly I do want to reiterate my gratitude for making it open and leaving it going. Not enough folks do this, you are one of the good guys!

**Comment by Sybrand** [comment]
> Hi, I had no idea that this was not the official tool LOL, My own fault for not asking, as I got it (The link) from Neal, and should have simply asked him about it. When he first told us (The national modelling team), about it, I posted the URL in our discord in our list of helpful modelling tools, and since then I use it every day (Please do not feel any obligation because of this - I know what it is like to maintain a GitHub project past its intended purpose and expected prototype lifecycle, as many of the critical tools NWT uses are exactly that, prototypes that worked too well to die, that became mission critical tools.)
> 
> I do not want you to feel any extra pressure to work on this project, as a thick & dirty fingers tool, it works perfectly. But.... there are a select few, mostly the WISE & CWFIS teams nerds (my self included) that likely pop the tool open to do quick validations of FWI etc. So it has a few users despite the fact that the codebase has moved on to BC Apps on mobile.
> 
> Lastly I do want to reiterate my gratitude for making it open and leaving it going. Not enough folks do this, you are one of the good guys!

I'm sure Neal is very busy at the moment!

I've quickly modified the version running at https://sybrand.github.io/ ;
- I've changed the "FWI" page to FFMC - since that's what it's really doing right now. (Would love to do a real FWI if I have the time)
- I've modified rain to increment in 0.5 increments.
- I've modified the FFMC output to display 2 decimal places.

Please give it a whirl and throw me a thumbs up if it works for you.

It's really easy to add small features like this - so feel free to reach out if there's anything you want me to add to the tool. 

Maybe we can have a conversation with Neal about rolling some features into FBP Go when things quiet down, or spinning up something that's more focused on the nerds.

**Comment by spydmobile** [comment]
Works great, and made it even easier to check my calcs this am! Thank you very much :D
